name: 'VoidGenPlus'
version: '3.0.0'
main: 'de.xtkq.voidgen.VoidGenPlus'
api-version: 1.13
load: STARTUP

author: 'xtkq'
website: 'https://github.com/OneCraftES/VoidGenPlus'
generator: VoidGenPlus
commands: {}
permissions: {}
depend: [ Multiverse-Core ]